### ISSUE TITLE
can there be infdev?

### ISSUE THREAD

**Issue by broiscool** [LAX1DUDE/eaglercraft#104]

**Comment by LAX1DUDE** [comment]
Dude stop opening issues are you like 5 years old? you already opened issues about alpha and beta on two completely separate occasions and I even marked it as an enhancement to add in the future even though it is off topic. The future is not right now, please leave us all alone.

[https://github.com/LAX1DUDE/eaglercraft/issues/65](https://github.com/LAX1DUDE/eaglercraft/issues/65)
[https://github.com/LAX1DUDE/eaglercraft/issues/16](https://github.com/LAX1DUDE/eaglercraft/issues/16)
