### ISSUE TITLE
Blocks wouldn't drop or mobs didn't drop anything in my server

### ISSUE THREAD

**Issue by GhostFire2177** [LAX1DUDE/eaglercraft#110]
I didn't et stuff in my inventory when I broke blocks

**Comment by GhostFire2177** [comment]
How do I also boost my fps in my game

**Comment by LAX1DUDE** [comment]
what server, be specific, give us a decent paragraph or two, at least five sentences describing the context of this question and what server it is and where it came from and who's running it
