### ISSUE TITLE
Low Frames

### ISSUE THREAD

**Issue by GhostFire2177** [LAX1DUDE/eaglercraft#111]
Is there a way to boost my frames because I get about 10-15 frames.

**Comment by sussygamedeveloper** [comment]
@GhostFire2177 Yes. do that, but make sure you don't have any other tabs open, and set the performance to max fps.

**Comment by LAX1DUDE** [comment]
Buffer Antialiasing: Auto
Graphics: Fast
Smooth Lighting: Off
Fog: Off
Clouds: Off
Render Distance: try small or tiny, but tiny is best
Performance: Max FPS
Particles: Minimal
