### ISSUE TITLE
Can't break/interact with blocks on most servers

### ISSUE THREAD

**Issue by Memecrash** [LAX1DUDE/eaglercraft#112]
Yes, this is likely a server-side issue and not an eaglecraft issue. But on many survival servers when i try to break a block it will reappear and no item drops when i try to open a chest the inventory instantly closes when i try to place a block it vanishes. My game runs at 120 fps and I lowered video settings so the gameplay is smooth. Do you know how to fix this if it is an eaglecraft issue.

**Comment by Memecrash** [comment]
I can list servers, show footage etc. if you want some. Most issues happen in servers where you have to type IPs. not forked servers that have .repl.co in the URL.

**Comment by LAX1DUDE** [comment]
it's spawn protection or lag and it's not my problem because these are 3rd party servers, find who's running the server you're on and complain about this to them instead

**Comment by Memecrash** [comment]
oh ok
