### ISSUE TITLE
Deploy on Heroku or Railway.app

### ISSUE THREAD

**Issue by pntang** [LAX1DUDE/eaglercraft#113]
Hi,I wanna deploy on [Heroku](https://www.heroku.com) or [Railway.app](railway.app)🤔

**Comment by pntang** [comment]
btw,Railway supports Docker

**Comment by LAX1DUDE** [comment]
[https://github.com/ayunami2000/eaglercraft-replit](https://github.com/ayunami2000/eaglercraft-replit)

**Comment by LAX1DUDE** [comment]
> But I wanna deploy this project with one click😂

If that's your attitude I'm not gonna help you

**Comment by pntang** [comment]
> > But I wanna deploy this project with one click😂
> 
> If that's your attitude I'm not gonna help you

Thank you,I'll deploy it myself  :p

**Comment by pntang** [comment]
> This will do what you want
> 
> https://github.com/ayunami2000/eaglercraft-replit

Sorry,I found a instruction:https://g.eags.us/eaglercraft/servers/viewtopic.php?f=3&t=73
Thank u!ヾ(•ω•`)o
