### ISSUE TITLE
AudioListener error

### ISSUE THREAD

**Issue by ethanaobrien** [LAX1DUDE/eaglercraft#116]
The URL to this fork's GitHub repository is: https://github.com/LAX1DUDE/eaglercraft

Copied and pasted message. This did happen more than once.

I'd recommend just placing a try/catch around this function so that if it does fail it won't crash the whole game.

Native Browser Exception
----------------------------------
  Line: 15823:393
  Type: TypeError
  Message: Failed to execute 'setPosition' on 'AudioListener': The provided float value is non-finite.
----------------------------------

TypeError: Failed to execute 'setPosition' on 'AudioListener': The provided float value is non-finite.
    at AudioListener.setPosition (<anonymous>)
    at API (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:1087:294)
    at AOv (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:1908:478)
    at A8O (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:1458:239)
    at Buo (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:1453:134)
    at Bhf (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:68:395)
    at Bxt (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:67:184)
    at TeaVMThread.runner (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:23:404)
    at TeaVMThread.run (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:15824:111)
    at TeaVMThread.resume (https://eaglercraft-server.ethanobrien7.repl.co/classes.js:15824:9)

eaglercraft.version = "22w04b"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "YeegVool17gh"
eaglercraft.channel = "YeegVool17_475"

window.minecraftOpts = ["game_frame","assets.epk","CgAACQAHc2VydmVycwoAAAABCAAKZm9yY2VkTU9URAAVWW91ciBNaW5lY3JhZnQgU2VydmVyAQALaGlkZUFkZHJlc3MBCAACaXAANHdzczovL2VhZ2xlcmNyYWZ0LXNlcnZlci5ldGhhbm9icmllbjcucmVwbC5jby9zZXJ2ZXIIAARuYW1lABBNaW5lY3JhZnQgU2VydmVyAAA="]

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14388.52.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.91 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 665
window.innerWidth = 1366
window.innerHeight = 665
window.outerWidth = 1366
window.outerHeight = 768
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 768
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = [object WebGL2RenderingContext]

window.location.href = https://eaglercraft-server.ethanobrien7.repl.co/
window.location.ancestorOrigins = {}

----- Begin Minecraft Config -----
CgAAAQAUc2VlbkFja25vd2xlZGdlbWVudHMBAA==
----- End Minecraft Config -----

window.minecraftServer = wss://eaglercraft-server.ethanobrien7.repl.co/server

**Comment by LAX1DUDE** [comment]
what is the last modified date on your replit, I committed a potential fix for this issue but did not advance the title screen and crash report version number because I'm a lazy idiot 

[https://github.com/LAX1DUDE/eaglercraft/issues/102](https://github.com/LAX1DUDE/eaglercraft/issues/102)

**Comment by ethanaobrien** [comment]
I updated it earlier today, before the crash occurred

**Comment by LAX1DUDE** [comment]
> I updated it earlier today, the crash occurred after I had updated it

[https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)
