### ISSUE TITLE
Need help creating private server on Chromebook without Replit

### ISSUE THREAD

**Issue by IcyonGit** [LAX1DUDE/eaglercraft#122]
Not much of an issue, but I need help with creating a private server without replit because my school has it blocked. If any of you lovely people can help please do. Thanks in advance.

**Comment by LAX1DUDE** [comment]
you can't, there's no java, the only way to get java on a chromebook is to first factory reset your chromebook and unregister it from your school and then also disable the virus protection which will get you in trouble. I am currently working on singleplayer, I'm hoping to do a successful first test of the code sometime tonight and I will hopefully release a working singleplayer version of eaglercraft in a few days or weeks

**Comment by IcyonGit** [comment]
> you can't, there's no java, the only way to get java on a chromebook is to first factory reset your chromebook and unregister it from your school and then also disable the virus protection which will get you in trouble. I am currently working on singleplayer, I'm hoping to do a successful first test of the code sometime tonight and I will hopefully release a working singleplayer version of eaglercraft in a few days or weeks

Fair enough, Thnks anyways. Love what you're doing here tho.

**Comment by French-Cat** [comment]
@IcyonGit You could always host your server on something at home and use something like
https://duckdns.org for the domain.
