### ISSUE TITLE
I cannot type

### ISSUE THREAD

**Issue by Calicay** [LAX1DUDE/eaglercraft#123]
I cant type when I enter the game. It asks me to press a key to enable sound but when I do it does not go to the next screen.

**Comment by LAX1DUDE** [comment]
click

**Comment by Calicay** [comment]
Even when I do that, it wont let me type in my new username and things.

**Comment by LAX1DUDE** [comment]
I don't own any of the available public server sites for eaglercraft, please talk to whoever owns the specific site you are experiencing this problem on and ask them to look into it
