### ISSUE TITLE
Add Singleplayer

### ISSUE THREAD

**Issue by Calicay** [LAX1DUDE/eaglercraft#125]

**Comment by ReadingFear** [comment]
Couldn't you have read the other millions of "OmG aDd SiNgLePlaYer" issues opened by idiots like you before opening your own?

**Comment by LAX1DUDE** [comment]
@Calicay Shut the fuck up

These here are all duplicate issues of your "Add Singleplayer" shitpost, all of which you could've read but you still chose to make a new one:

Issue [#124](https://github.com/LAX1DUDE/eaglercraft/issues/124)
Issue [#108](https://github.com/LAX1DUDE/eaglercraft/issues/108)
Issue [#106](https://github.com/LAX1DUDE/eaglercraft/issues/106)
Issue [#79](https://github.com/LAX1DUDE/eaglercraft/issues/79)
Issue [#46](https://github.com/LAX1DUDE/eaglercraft/issues/46)
Issue [#45](https://github.com/LAX1DUDE/eaglercraft/issues/45)
Issue [#30](https://github.com/LAX1DUDE/eaglercraft/issues/30)
Issue [#119](https://github.com/LAX1DUDE/eaglercraft/issues/119)
Issue [#7](https://github.com/LAX1DUDE/eaglercraft/issues/7)

Get the fuck off of this site

**Comment by m7md1112** [comment]
Hi um how do I keep all my items in my inventory when I close my private server I am having a issue with that, if anyone can help?

**Comment by Calicay** [comment]
OMG. I am so offended.(NOT!!!) Listen here mother f#$@er. I dont have time for your sh$t right now. So shut your b#$@! a$$ up,OK!?

**Comment by Calicay** [comment]
How bout you make ME BITCH!
