### ISSUE TITLE
Inventory save 

### ISSUE THREAD

**Issue by m7md1112** [LAX1DUDE/eaglercraft#126]
Hi um how do I save all my items in my inventory when I close my private server I am having a issue with that, if anyone can help? I'm using Replit.

**Comment by LAX1DUDE** [comment]
This repository has nothing to do with replit that's ayunami2000's thing

 [https://github.com/ayunami2000/eaglercraft-replit/](https://github.com/ayunami2000/eaglercraft-replit/issues)

post your issues on his repository

**Comment by m7md1112** [comment]
ok thanks
