### ISSUE TITLE
Compiling an offline download version

### ISSUE THREAD

**Issue by ReadingFear** [LAX1DUDE/eaglercraft#128]
Hi, I'm wondering if there's any utilities or methods I can compile my own offline download version, like the one in stable-download.

Sorry if there's already a tool posted and I'm just wasting your time.

**Comment by LAX1DUDE** [comment]
there's no compiler

copy paste the contents of classes.js over the existing script tag of the offline file and then base64 encode assets.epk and paste it over the existing base64 that's in the tag at the end of the <body> element of the offline file

**Comment by ReadingFear** [comment]
Ok, thank you.

**Comment by LAX1DUDE** [comment]
> Ok, thank you.

sorry my answer was pretty confusing, I didn't do a very good job explaining which tags I was actually talking about and what a tag in this context even means in the first place. Feel free to follow up on this thread if I confused you

**Comment by ReadingFear** [comment]
No, it's fine. I got it working.
