### ISSUE TITLE
the server

### ISSUE THREAD

**Issue by bellugga** [LAX1DUDE/eaglercraft#129]
thes server does not work it says that there is a problem like ............  the server and do u know some public servers?

**Comment by bellugga** [comment]
oh if u read this Lax1dude i cant make severs have any answers for that? oh and the server is like to glitchy and everything resets every day

**Comment by bellugga** [comment]
it still does not work idk why can u help me ?
it never stops loadinng it only says connecting

**Comment by French-Cat** [comment]
"thes server does not work it says that there is a problem like" gives no information
Your going to need to specify whats wrong.

**Comment by LAX1DUDE** [comment]
> oh if u read this Lax1dude i cant make severs have any answers for that? oh and the server is like to glitchy and everything resets every day

it's not my problem, talk to who owns the server, and if you own the server then please figure this out yourself, all the resources you need to figure it out have been made available to you on a variety of different platforms

**Comment by bellugga** [comment]
ok thx
