### ISSUE TITLE
hi how can i get the single player?

### ISSUE THREAD

**Issue by stupidkidwhoisprobablyinthirdgrade** [LAX1DUDE/eaglercraft#130]
hello, i am a stupid litle kid who desperatly wants to play mine-craft at schol. ihave no idea how to use this site, so i am ignoring the otherr tens of thosands of issues which are asing for the exactt same thing and posting my own. how can i get the sing-elplayer?

**Comment by ChobasCode** [comment]
Hello do you need help

**Comment by ethanaobrien** [comment]
Issue https://github.com/LAX1DUDE/eaglercraft/issues/125
Issue https://github.com/LAX1DUDE/eaglercraft/issues/124
Issue https://github.com/LAX1DUDE/eaglercraft/issues/108
Issue https://github.com/LAX1DUDE/eaglercraft/issues/106
Issue https://github.com/LAX1DUDE/eaglercraft/issues/79
Issue https://github.com/LAX1DUDE/eaglercraft/issues/46
Issue https://github.com/LAX1DUDE/eaglercraft/issues/45
Issue https://github.com/LAX1DUDE/eaglercraft/issues/30
Issue https://github.com/LAX1DUDE/eaglercraft/issues/119
Issue https://github.com/LAX1DUDE/eaglercraft/issues/7

**Comment by stupidkidwhoisprobablyinthirdgrade** [comment]
Do you guys know what a joke is?

**Comment by LAX1DUDE** [comment]
> Hello do you need help

@ChobasCode I don't know what you're planning here but if you try to burn me down again you're gonna lose
