### ISSUE TITLE
Is it possible to at least run 1.9?

### ISSUE THREAD

**Issue by Itzkhaliz** [LAX1DUDE/eaglercraft#136]
I really miss the combat update so is it possible to update to 1.9?

**Comment by ayunami2000** [comment]
We are working on (or were, before singleplayer) 1.8.9, so no the chances of us porting 1.9 after 1.8 are slim (if we even ever do get around to porting it)

**Comment by Itzkhaliz** [comment]
hmmmmm ok no problem
