### ISSUE TITLE
ReadTimeoutException : null 

### ISSUE THREAD

**Issue by isrealin** [LAX1DUDE/eaglercraft#138]
what does thim mean bc its preventing me to log on to the server at times that go for hours

**Comment by LAX1DUDE** [comment]
> what does thim mean bc its preventing me to log on to the server at times that go for hours

not my problem, the server you are trying to play on is broken, you need to talk to who owns the server there's nothing anyone on this site can do about a broken server

if it only happens at school then it is a firewall problem, there's no way to fix it if it's a problem with your school's internet
