### ISSUE TITLE
The commands 

### ISSUE THREAD

**Issue by CloudClownn** [LAX1DUDE/eaglercraft#139]
what happened to the commands like /back for tpa I have played without them and it's hard to play the game without them plz put them back I beg you

**Comment by ReadingFear** [comment]
This isn't a problem with eaglercraft, it's a problem with you having no clue whatsoever how Minecraft servers and plugins work. Install a /back plugin.

**Comment by ReadingFear** [comment]
https://dev.bukkit.org/projects/safeback
https://bukkit.fandom.com/wiki/Installing_Plugins

**Comment by LAX1DUDE** [comment]
> what happened to the commands like /back for tpa I have played without them and it's hard to play the game without them plz put them back I beg you

the plugin for /tpa and /home and /back is called essentials

[https://wiki.mc-ess.net/wiki/Downloads](https://wiki.mc-ess.net/wiki/Downloads)
