### ISSUE TITLE
Eaglercraft server crashing repeatedly

### ISSUE THREAD

**Issue by mineflayer** [LAX1DUDE/eaglercraft#141]
I am hosting my server on repl.it and I haven't made any changes to it but it still crashes, i've tried to use other optimized forks for repl.it but that does not work either. 
------- LOG --------
 bash main.sh
ensuring old server process is truly closed...
nginx: [alert] could not open error log file: open() "/tmp/nginx/error.log" failed (2: No such file or directory)
2022/03/02 01:37:11 [notice] 33#33: signal process started
2022/03/02 01:37:11 [error] 33#33: open() "/tmp/nginx/nginx.pid" failed (2: No such file or directory)
deleting old backup files...
verifying files...
files exist! proceeding...
backing up old files...
checking if file still works...
site is still up! downloading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.8M  100 28.8M    0     0  16.1M      0  0:00:01  0:00:01 --:--:-- 16.1M
extracting zip...
Archive:  stable-download.zip
   creating: java/
   creating: java/bukkit_command/
  inflating: java/bukkit_command/banned-ips.txt  
  inflating: java/bukkit_command/banned-players.txt  
  inflating: java/bukkit_command/bukkit.yml  
  inflating: java/bukkit_command/craftbukkit-1.5.2-R1.0.jar  
  inflating: java/bukkit_command/help.yml  
 extracting: java/bukkit_command/ops.txt  
 extracting: java/bukkit_command/permissions.yml  
 extracting: java/bukkit_command/run.bat  
  inflating: java/bukkit_command/server.properties  
  inflating: java/bukkit_command/spigot.yml  
 extracting: java/bukkit_command/white-list.txt  
   creating: java/bungee_command/
  inflating: java/bungee_command/bungee-dist.jar  
  inflating: java/bungee_command/config.yml  
 extracting: java/bungee_command/run.bat  
   creating: web/
 extracting: web/assets.epk          
  inflating: web/classes.js          
  inflating: web/classes.js.map      
  inflating: web/index.html          
deleting original zip file...
verifying files...
files exist! proceeding...
restoring servers from backup so you dont lose data...
ensuring that bungeecord is hosting on the correct port...
starting bungeecord...
/home/runner/eaglercraft-server
configuring local website...
setting default server...
starting nginx...
starting bukkit...
229 recipes
27 achievements
01:38:07 [INFO] Starting minecraft server version 1.5.2
01:38:09 [WARNING] To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
01:38:10 [INFO] Loading properties
01:38:10 [INFO] Default game type: SURVIVAL
01:38:11 [INFO] Generating keypair
01:38:24 [INFO] Starting Minecraft server on *:25569
01:38:41 [INFO] This server is running CraftBukkit version git-Bukkit-1.5.2-R1.0-b2788jnks (MC: 1.5.2) (Implementing API version 1.5.2-R1.0)
01:38:45 [WARNING] **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
01:38:46 [WARNING] The server will make no attempt to authenticate usernames. Beware.
01:38:46 [WARNING] While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
01:38:46 [WARNING] To change this, set "online-mode" to "true" in the server.properties file.
01:38:49 [INFO] Preparing level "world"
01:38:55 [INFO] Preparing start region for level 0 (Seed: -855162288097023011)
01:39:01 [INFO] Preparing spawn area: 0%
01:39:02 [INFO] Preparing spawn area: 0%
01:39:03 [INFO] Preparing spawn area: 0%
01:39:05 [INFO] Preparing spawn area: 0%
01:39:06 [INFO] Preparing spawn area: 0%
01:39:07 [INFO] Preparing spawn area: 0%
01:39:08 [INFO] Preparing spawn area: 4%
01:39:09 [INFO] Preparing spawn area: 4%
01:39:10 [INFO] Preparing spawn area: 4%
01:39:11 [INFO] Preparing spawn area: 4%
01:39:13 [INFO] Preparing spawn area: 8%
01:39:14 [INFO] Preparing spawn area: 8%
01:39:15 [INFO] Preparing spawn area: 12%
01:39:16 [INFO] Preparing spawn area: 12%
01:39:17 [INFO] Preparing spawn area: 12%
01:39:18 [INFO] Preparing spawn area: 12%
01:39:19 [INFO] Preparing spawn area: 16%
01:39:20 [INFO] Preparing spawn area: 16%
01:39:22 [INFO] Preparing spawn area: 16%
01:39:23 [INFO] Preparing spawn area: 16%
01:39:24 [INFO] Preparing spawn area: 20%
01:39:25 [INFO] Preparing spawn area: 20%
01:39:26 [INFO] Preparing spawn area: 20%
01:39:27 [INFO] Preparing spawn area: 20%
01:39:28 [INFO] Preparing spawn area: 20%
01:39:29 [INFO] Preparing spawn area: 24%
01:39:31 [INFO] Preparing spawn area: 24%
01:39:32 [INFO] Preparing spawn area: 25%
>
01:39:33 [INFO] Preparing spawn area: 28%
01:39:34 [INFO] Preparing spawn area: 29%
01:39:35 [INFO] Preparing spawn area: 33%
01:39:36 [INFO] Preparing spawn area: 33%
01:39:38 [INFO] Preparing spawn area: 33%
01:39:40 [INFO] Preparing spawn area: 33%
01:39:41 [INFO] Preparing spawn area: 33%
01:39:43 [INFO] Preparing spawn area: 33%
01:39:45 [INFO] Preparing spawn area: 33%
01:39:47 [INFO] Preparing spawn area: 33%
01:39:48 [WARNING] Could not get information about this CraftBukkit version; perhaps you are running a custom one?: IOException
01:39:48 [INFO] Preparing spawn area: 33%
01:39:52 [INFO] Preparing spawn area: 33%
01:39:53 [INFO] Preparing spawn area: 33%
01:39:55 [INFO] Preparing spawn area: 33%
01:39:57 [INFO] Preparing spawn area: 33%
01:39:58 [INFO] Preparing spawn area: 33%
01:39:59 [INFO] Preparing spawn area: 33%
01:40:04 [INFO] Preparing spawn area: 33%
01:40:05 [INFO] Preparing spawn area: 33%
01:40:07 [INFO] Preparing spawn area: 33%
01:40:08 [INFO] Preparing spawn area: 33%
01:40:10 [INFO] Preparing spawn area: 33%
01:40:12 [INFO] Preparing spawn area: 33%
01:40:14 [INFO] Preparing spawn area: 33%
01:40:18 [INFO] Preparing spawn area: 33%
01:40:20 [INFO] Preparing spawn area: 33%
01:40:21 [INFO] Preparing spawn area: 37%
01:40:24 [INFO] Preparing spawn area: 37%
01:40:27 [INFO] Preparing spawn area: 37%
01:40:29 [INFO] Preparing spawn area: 37%
01:40:35 [INFO] Preparing spawn area: 37%
01:40:39 [INFO] Preparing spawn area: 37%
01:40:43 [INFO] Preparing spawn area: 37%
01:40:47 [INFO] Preparing spawn area: 37%
01:40:53 [INFO] Preparing spawn area: 37%
01:41:02 [INFO] Preparing spawn area: 37%
01:41:14 [INFO] Preparing spawn area: 37%
01:41:33 [WARNING] Could not get latest artifact information: IOException
01:41:38 [INFO] Preparing spawn area: 37%
01:42:07 [INFO] Preparing spawn area: 37%
01:42:26 [INFO] Preparing spawn area: 37%
01:43:24 [INFO] Preparing spawn area: 37%
main.sh: line 88:    83 Killed                  java -Xmx512M -Xms512M -jar craftbukkit-1.5.2-R1.0.jar
/home/runner/eaglercraft-server
killing bungeecord and nginx...
done!
------ END OF LOG ------

**Comment by LAX1DUDE** [comment]
I don't maintain the replit stuff ask ayunami2000

[https://github.com/ayunami2000/eaglercraft-replit](https://github.com/ayunami2000/eaglercraft-replit)
