### ISSUE TITLE
Website Broken

### ISSUE THREAD

**Issue by hackinghacker1** [LAX1DUDE/eaglercraft#146]
whenever i go on https://[g.eags.us](https://g.eags.us/eaglercraft/)/eaglercraft/ it says "The connection for this site is not secure" with an error code of "ERR_SSL_PROTOCOL_ERROR"

**Comment by LAX1DUDE** [comment]
> whenever i go on https://[g.eags.us](https://g.eags.us/eaglercraft/)/eaglercraft/ it says "The connection for this site is not secure" with an error code of "ERR_SSL_PROTOCOL_ERROR"

you're browser's broken
