### ISSUE TITLE
how to host a sever with friends??

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [LAX1DUDE/eaglercraft#147]

**Comment by primitt** [comment]
https://github.com/LAX1DUDE/eaglercraft#installing
https://youtu.be/Zsnv8YskjMA
https://github.com/LAX1DUDE/eaglercraft/issues/122
https://github.com/LAX1DUDE/eaglercraft/issues/107
https://github.com/LAX1DUDE/eaglercraft/issues/105
https://github.com/LAX1DUDE/eaglercraft/issues/75
https://github.com/LAX1DUDE/eaglercraft/issues/59
https://github.com/LAX1DUDE/eaglercraft/issues/52
https://github.com/LAX1DUDE/eaglercraft/issues/31
https://github.com/LAX1DUDE/eaglercraft/issues/32
https://github.com/LAX1DUDE/eaglercraft/issues/26
https://github.com/LAX1DUDE/eaglercraft/issues/27
https://github.com/LAX1DUDE/eaglercraft/issues/14

**Comment by primitt** [comment]
Just frikin read oml
