### ISSUE TITLE
Website not responding

### ISSUE THREAD

**Issue by Chancelorrayens** [LAX1DUDE/eaglercraft#148]
When I try and open the url or open the website it is not opening/responding

**Comment by LAX1DUDE** [comment]
elaborate please

**Comment by Chancelorrayens** [comment]
nevormind the school blocked it after a day is there something I can do about it or could you like slightly change the URL?

**Comment by Chancelorrayens** [comment]
also I just opened the offline version of it how can i get the server ip of the server I was on before the school blocked it?

**Comment by Chancelorrayens** [comment]
(I need the server ip because the place where you have all of the other ips listed is blocked

**Comment by ReadingFear** [comment]
> nevormind the school blocked it after a day is there something I can do about it or could you like slightly change the URL?

Get the offline download version (https://github.com/LAX1DUDE/eaglercraft/raw/main/stable-download/Offline_Download_Version.html)

**Comment by ReadingFear** [comment]
> also I just opened the offline version of it how can i get the server ip of the server I was on before the school blocked it?

Remember it or look for where you got it from
