### ISSUE TITLE
not really a issue but more like a question

### ISSUE THREAD

**Issue by isrealin** [LAX1DUDE/eaglercraft#149]
i want to make a new server so my friends and i can play on but i have no clue how to make a new server that works like the devualt one. i've tried to get into the servers in the servers list but it allways bars are allways blue and moving.
thank you  and sorry if this makes no sense.

**Comment by isrealin** [comment]
i just want to have something else to do

**Comment by ethanaobrien** [comment]
https://github.com/LAX1DUDE/eaglercraft/issues/147
https://github.com/LAX1DUDE/eaglercraft/issues/132
https://github.com/LAX1DUDE/eaglercraft/issues/129
https://github.com/LAX1DUDE/eaglercraft/issues/127
https://github.com/LAX1DUDE/eaglercraft/issues/122
https://github.com/LAX1DUDE/eaglercraft/issues/107
https://github.com/LAX1DUDE/eaglercraft/issues/105
https://github.com/LAX1DUDE/eaglercraft/issues/75
https://github.com/LAX1DUDE/eaglercraft/issues/59
https://github.com/LAX1DUDE/eaglercraft/issues/52
https://github.com/LAX1DUDE/eaglercraft/issues/31
https://github.com/LAX1DUDE/eaglercraft/issues/32
https://github.com/LAX1DUDE/eaglercraft/issues/26
https://github.com/LAX1DUDE/eaglercraft/issues/27
https://github.com/LAX1DUDE/eaglercraft/issues/14

https://github.com/LAX1DUDE/eaglercraft#installing
https://youtu.be/Zsnv8YskjMA


1. download https://github.com/LAX1DUDE/eaglercraft/blob/main/stable-download/stable-download.zip
2. unzip it
3. open `java/bukkit_command/run.bat`
4. open `java/bungee_command/run.bat`
5. open the offline download html
6. click `add server` and enter your hostname, a `:`, and then the port. it should have a message in one of the command prompts of the programs above that says `listening for websockets on 0.0.0.0:PORT`. the port is the number after the `0.0.0.0:`
7. click join
8. look at the other thousand issues before opening

**Comment by isrealin** [comment]
is there any hope if the run.bat thing doues not work

**Comment by LAX1DUDE** [comment]
> is there any hope if the run.bat thing doues not work

what do you even mean, if you're on mac or linux just copy and run the command that's inside the two bat files, the command in the files is the same command you run in linux or mac you just have to copy paste it into the shell which is trivial

**Comment by Chancelorrayens** [comment]
can you do it on a chromebook?

**Comment by ethanaobrien** [comment]
no, you cannot
