### ISSUE TITLE
Using Assets.epk with offline html download? 

### ISSUE THREAD

**Issue by Animationss** [LAX1DUDE/eaglercraft#150]
The title practically sums up what I wanted to say
How does one use assets.epk with a offline download of eaglercraft

**Comment by LAX1DUDE** [comment]
see issue [https://github.com/LAX1DUDE/eaglercraft/issues/128](https://github.com/LAX1DUDE/eaglercraft/issues/128)

base64 encode the epk file and paste the base64 string into the \<div\> tag at the end of html in place of the existing base64

you need to redo this process each time you update it
