### ISSUE TITLE
Hello there! Is there a server.jar file to use so I can host my server? 

### ISSUE THREAD

**Issue by mehdinchina420** [LAX1DUDE/eaglercraft#153]
I already host a vanilla server that I would use to play on with some friends at school but I don't find the server.jar that I could host.

**Comment by LAX1DUDE** [comment]
There is no 'server.jar', please read the documentation, it was presented to you the second you found my repository and if you had checked the list of closed issues you would've also seen that I've already answered this question a dozen times

https://github.com/LAX1DUDE/eaglercraft#installing
https://youtu.be/Zsnv8YskjMA

https://github.com/LAX1DUDE/eaglercraft/issues/122
https://github.com/LAX1DUDE/eaglercraft/issues/107
https://github.com/LAX1DUDE/eaglercraft/issues/105
https://github.com/LAX1DUDE/eaglercraft/issues/75
https://github.com/LAX1DUDE/eaglercraft/issues/59
https://github.com/LAX1DUDE/eaglercraft/issues/52
https://github.com/LAX1DUDE/eaglercraft/issues/31
https://github.com/LAX1DUDE/eaglercraft/issues/32
https://github.com/LAX1DUDE/eaglercraft/issues/26
https://github.com/LAX1DUDE/eaglercraft/issues/27
https://github.com/LAX1DUDE/eaglercraft/issues/14

**Comment by mehdinchina420** [comment]
Oh ok, sorry!
