### ISSUE TITLE
Mob inside mob spawner doesn't render

### ISSUE THREAD

**Issue by iAmInActions** [LAX1DUDE/eaglercraft#17]
The mobs that usually spin around in mob spawners do not render. This is not a server side issue.

**Comment by LAX1DUDE** [comment]
I removed the code because of serialization problems

**Comment by LAX1DUDE** [comment]
Fixed: [https://github.com/LAX1DUDE/eaglercraft/commit/f764d3d3d20064ce8d90346a5b0bdc5e1caea76c](https://github.com/LAX1DUDE/eaglercraft/commit/f764d3d3d20064ce8d90346a5b0bdc5e1caea76c)
