### ISSUE TITLE
in collabvm we cant type anything

### ISSUE THREAD

**Issue by LeGamermc** [LAX1DUDE/eaglercraft#18]

**Comment by LAX1DUDE** [comment]
what makes you think this is a bug located in this game's source code and not in your virtualization setup

but I think the real question is, why are you using a browser-based virtual machine terminal to run a second browser inside the virtual machine you're already accessing on your real computer's browser and then playing a browser game on that second browser while literally using the browser on your real computer to view the screen of the virtual machine

**Comment by DESKTOPGOOOSE** [comment]
that's a good point, is your computer not performance now enough to run minecraft 1.5.2? i could run that on some 2007 windows vista home basic machine
the dev has literally owned you, that is amazing.
