### ISSUE TITLE
The game shows unable to connect

### ISSUE THREAD

**Issue by kiwlk** [LAX1DUDE/eaglercraft#24]
When I try to play from home it works but when i play from school it doesn't work

**Comment by LAX1DUDE** [comment]
Please elaborate, what server doesn't it connect to and what link are you playing on. how am I supposed to just know exactly what's going on here, you didn't even put a period or capitalize that 'i' I can't help you if you literally spend 10 seconds on your description

**Comment by kiwlk** [comment]
Sorry, I was in school so I didn't have much time to write my question. Here is my elaborated version:

I'm connected to my school's internet, and when I load up the demo version, it seems to be fine. This changes, though.
As I try to load into the survival server, the loading screen gets stuck on the "connecting to server" message.

![Screenshot 2022-01-27 1 52 26 PM](https://user-images.githubusercontent.com/98498570/151424979-3f56600a-85bf-408a-bb3a-d7743593f18e.png)

During this period of time, the tab freezes. 
After around 1-2 minutes, the screen changes and pops up with this message:

![image](https://user-images.githubusercontent.com/98498570/151425183-8b021e2e-5c49-4309-8c81-d37316ed5252.png)

Was there something I did wrong? Please help.

**Comment by LAX1DUDE** [comment]
The servers are overloaded, I'm probably gonna have to take them down for a while. Your school might've set up a firewall to block ws:// and wss:// URLs from loading because websockets are mainly used for online browser games (afaik) so that might be the problem too

**Comment by kiwlk** [comment]
Thank you.
