### ISSUE TITLE
private servers?

### ISSUE THREAD

**Issue by eldercraftlover** [LAX1DUDE/eaglercraft#27]
How can you make a private server

**Comment by LAX1DUDE** [comment]
your question has already been answered three times stop spamming

[Issue #26](https://github.com/LAX1DUDE/eaglercraft/issues/26)
[Issue #22](https://github.com/LAX1DUDE/eaglercraft/issues/22)
[Issue #14](https://github.com/LAX1DUDE/eaglercraft/issues/14)

**Comment by eldercraftlover** [comment]
sorry
