### ISSUE TITLE
Game Freezes during connect to server

### ISSUE THREAD

**Issue by Yamipengui** [LAX1DUDE/eaglercraft#28]
when connecting to the server through the local ip address it loads up just fine. But if i try from my ipv4 address which has been port forwarded to the correct port, it freezes the game.

**Comment by LAX1DUDE** [comment]
It's because NAT loopback is not enabled on your router, you can't connect to your public IP address from a private IP address located on the same subnet that the public IP address is set to NAT

[https://en.wikipedia.org/wiki/Hairpinning](https://en.wikipedia.org/wiki/Hairpinning)
