### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Death-The-Kid-Glitched** [LAX1DUDE/eaglercraft#29]
_I know you said don't open anymore issues but this has been happening since before you said that and I didn't know how to write an issue so I am now:_

I can only login once per day, anytime after that when I join I get stuck in about a ten chunk radius with only void around me, I can't login, hit, mine, or type anything in chat. All I can do is jump around and fall in the void (check the y value).
![Screenshot 2022-01-27 2 00 42 PM](https://user-images.githubusercontent.com/76791182/151567712-330a787d-4f93-4212-9368-c8d8940ff91e.png)

**Comment by 20plays** [comment]
This happens to me as well, with a java illegal access exeption shown in the logs

**Comment by LAX1DUDE** [comment]
I said they're overload and I said please don't open any issues. This has been a problem for just over 24h idk why you would expect me to find enough time by now to recreate the whole survival server with a lobby and multiple worlds on a whole different instance of linux. I'm just busy right now I'll fix it in a day or two

**Comment by JontayOfficial** [comment]
i know bro i was just replying im not dumb
