### ISSUE TITLE
Video tutorial for Private server creation?

### ISSUE THREAD

**Issue by Flash2149** [LAX1DUDE/eaglercraft#31]
I'm sorry to bother anyone or waste their time, its just that my small brain cant understand what's going on in the instructions for a private server

So I was wondering if someone could possibly make a video tutorial?

**Comment by ayunami2000** [comment]
Check out the FAQ channel in the discord server for a potentially clearer explanation. If you still want a video tutorial, respond to this issue again. If not, go ahead and close this issue.
