### ISSUE TITLE
Cannot get the bungee server to connect

### ISSUE THREAD

**Issue by primitt** [LAX1DUDE/eaglercraft#35]
So i get a  java.net.ConnectException whenever i try to log in
Console:
14:49:18 [INFO] Unable to initialize fancy terminal. To fix this on Windows, install the correct Microsoft Visual C++ 2008 Runtime
14:49:18 [INFO] NOTE: This error is non crucial, and BungeeCord will still function correctly! Do not bug the author about it unless you are still unable to get it working
14:49:18 [INFO] Enabled BungeeCord version unknown
14:49:18 [INFO] Enabled plugin EaglerSkins version 1.0.0 by LAX1DUDE
14:49:18 [INFO] Listening websockets on /0.0.0.0:80
14:49:19 [INFO] Listening on /127.11.0.1:54514
14:49:59 [INFO] websocket opened - /127.0.0.1:54534
14:49:59 [INFO] [primitt] <-> InitialHandler has connected
14:50:01 [INFO] [primitt] disconnected with: Could not connect to default server, please try again later: java.net.ConnectException
14:50:01 [INFO] [primitt] -> UpstreamBridge has disconnected
14:50:01 [INFO] websocket closed - /127.0.0.1:54534
>

**Comment by LAX1DUDE** [comment]
you're not running the bukkit server and/or you changed the port on the bukkit `server.properties` not to match the port in the server entry in the bungeecord `config.yml` anymore. You are required to run both the bukkit server and the bungeecord server on your system at the same time they are not interchangeable.

**Comment by primitt** [comment]
Hey thanks! I was able to make it run, but not able to run it on linux. Anything I have to do different to run it on linux? I get this error: cannot get bungee-dist.jar
P.S: I did chmod everything

**Comment by primitt** [comment]
Oh and, is it possible to externally connect to your server? If so, what do I need to do to connect (like what ports to portforward)?
