### ISSUE TITLE
music discs don't play

### ISSUE THREAD

**Issue by Abnumality** [LAX1DUDE/eaglercraft#39]
i can't attach the video because it's too big but basically the music disc goes in normally but no audio plays

**Comment by ayunami2000** [comment]
music discs are not supported right now in order to slim down the file size. same for all but title screen music. also all sounds are compressed to save space for faster downloading of resources and a smaller game overall.

**Comment by LAX1DUDE** [comment]
> music discs are not supported right now in order to slim down the file size. same for all but title screen music. also all sounds are compressed to save space for faster downloading of resources and a smaller game overall.

80% of the official game's size on disk is just the soundtrack, you can imagine how many times longer it would take to load the game every time you reload the page if the resources file's size was that much larger than it already is
