### ISSUE TITLE
you cant join other server other than the default ones on the site (https://g.eags.us/eaglercraft/)

### ISSUE THREAD

**Issue by nososho** [LAX1DUDE/eaglercraft#41]
you cant join other server other than the default ones on the site (https://g.eags.us/eaglercraft/)

**Comment by ayunami2000** [comment]
this is because your servers likely dont use wss

**Comment by nososho** [comment]
how can i apply wss to my servers then?

**Comment by LAX1DUDE** [comment]
Use nginx as a reverse proxy and either install [letsencrypt.org](https://letsencrypt.org/) or proxy the connection a second time through [cloudflare.com](https://cloudflare.com/) and enable free SSL in the proxy's outgoing connection configuration

**Comment by LAX1DUDE** [comment]
does this mean nothing to you

![https_wss](https://i.gyazo.com/39039a08b6d81d0fa488f61efce5e5e3.png)

**Comment by Adithr123** [comment]
Can u give us a .txt file with example servers?

**Comment by ayunami2000** [comment]
you can find public servers on the discord, link in the readme. @LAX1DUDE can you add that public servers are listed in the discord to the readme so others know
