### ISSUE TITLE
Client integrity calculation error

### ISSUE THREAD

**Issue by ExpLogan** [LAX1DUDE/eaglercraft#44]
I'm having trouble entering the survival server. It's only the survival server that will not let me in. Alternatively, the creative server still lets me in. Could someone tell me how to fix this? I entered the flag menu or whatever, but I don't know what to fix.
![Screenshot 2022-01-31 9 28 02 AM](https://user-images.githubusercontent.com/98755126/151811861-7e42c8d4-13e8-4d27-8d89-d852009069c3.png)

**Comment by LAX1DUDE** [comment]
> You can only play the survival server on https://g.eags.us/eaglercraft/

Yeah, people were making hacked clients specifically to target my survival server and I know it was targeted at me because they were beating NoCheatPlus which isn't installed by default on the server in the `stable-download` folder. So I implemented an extremely sensitive and hopelessly obfuscated hashing algorithm to make it extremely hard to join survival with any version of the code except the version on [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) that changes every few days

**Comment by ExpLogan** [comment]
But I wasn't spamming the n-word, in fact, i don't even know what you're talking about. I only said it once in an argument between a toxic. My friend is a racist, maybe it was him. But I swear I did not do that. **chrome://flags/#ash-debug-shortcuts** this is what I was using. No need to call me dumb.

**Comment by ExpLogan** [comment]
Besides, when I said it, it wasn't the hard R, so don't go around saying I said the n!gger word. Liars are quite annoying.

**Comment by ExpLogan** [comment]
I'd like to figure all of this out so I can appeal, because I feel as though I have been framed. I would like to talk this out like two regular human beings.

**Comment by LAX1DUDE** [comment]
I looked through the chat and you said it twice and the second time was with a hard R. You were also calling people faggots, and the problem with that for me is just that some people looking at this site are here for a demo and when they're greeted with constant slurs in the global chat it reflects badly on my ability to moderate my own software and deal with problematic 'hate speech' all over my platform in a way that doesn't reflect badly on my social priorities. It's impossible to unban your browser it's hard coded, so you need to reset your whole browser to unban it and then you can't log in as _E_ anymore

**Comment by ExpLogan** [comment]
Thank you for telling me this, Ill make sure to do it. And I won't say it anymore. Well, Faggot isnt that bad, but whatever. Thankyou, have a good one.
