### ISSUE TITLE
Base64 Serverlist string not decoding properly

### ISSUE THREAD

**Issue by 20plays** [LAX1DUDE/eaglercraft#48]
Hey there, just followed your instructions for a custom serverlist and am trying to decode the default string on base64decode.org, 
but it spits out some random characters. I tried editing around it, but the servers aren't showing up in the game. Here's a screenshot:

https://cdn.discordapp.com/attachments/805931591716175883/937777778240135198/base64.png

Thanks in advance!

**Comment by LAX1DUDE** [comment]
You have to paste the base64 in a text file and then upload the text file to the site, then it will allow you to decode it and download the binary as a file. It's confusing just download this copy of the default one that's already decoded for NBTExplorer - [servers_template.dat](https://github.com/LAX1DUDE/eaglercraft/raw/main/stable-download/servers_template.dat)
