### ISSUE TITLE
could not get into sevrer

### ISSUE THREAD

**Issue by loganz205** [LAX1DUDE/eaglercraft#49]
every time i try to play the sever it says could not connect to the server then says the sever address

**Comment by LAX1DUDE** [comment]
what page? what server? what address? what eaglercraft version? what network? I can't answer questions like this why do you think I just know what's going here with the information you provided. Unless you are using [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) and playing specifically on one of the two default servers, using a computer or network without any site blocking extensions, then this not my problem and you need to contact whoever is running the server and website that you are getting this error on

**Comment by loganz205** [comment]
> what page? what server? what address? what eaglercraft version? what network? I can't answer questions like this why do you think I just know what's going here with the information you provided. Unless you are using https://g.eags.us/eaglercraft/ and playing specifically on one of the two default servers, using a computer or network without any site blocking extensions, then this not my problem and you need to contact whoever is running the server and website that you are getting this error on

**Comment by loganz205** [comment]
shut up you a whole bitch stop being a lil bitch fr tho thinking your all big and bad ill beat your ass

**Comment by LAX1DUDE** [comment]
> shut up you a whole bitch stop being a lil bitch fr tho thinking your all big and bad ill beat your ass

lmao goodbye

**Comment by antiaim** [comment]
comedy gold
