### ISSUE TITLE
blocks I break don't drop

### ISSUE THREAD

**Issue by Azzy1700** [LAX1DUDE/eaglercraft#51]
when I  break blocks (for instant I break wood with my hands it doesn't drop) they don't drop

**Comment by sussygamedeveloper** [comment]
Its probably because of lag on your internet or the demo servers, or spawn protection.

**Comment by LAX1DUDE** [comment]
> Its probably because of lag on your internet or the demo servers, or spawn protection.

the servers are severely overloaded, I can’t afford to pay $100s of dollars more for slightly faster internet just to facilitate more piracy to a bunch of middle schoolers that I don’t even know. My area doesn’t have fiber or anything so the upload bandwidth required for running a big server is severely restricted by my ISP without an really expensive plan
