### ISSUE TITLE
can i make a server with out downloading anything 

### ISSUE THREAD

**Issue by broiscool** [LAX1DUDE/eaglercraft#52]

**Comment by sussygamedeveloper** [comment]
Not for the official project. But a fork named ayuncraft has vanilla server support via a web proxy. so if you create a minecraft 1.5.2 server with, lets say atrernos, and change the proxy to webmcproxy.glitch.me, then connect to the server, then yes you can.

**Comment by sussygamedeveloper** [comment]
didn't know, but i actually did it.
