### ISSUE TITLE
ADD CHAT FILTER

### ISSUE THREAD

**Issue by aydanmassa** [LAX1DUDE/eaglercraft#61]
I play this in school and most of the chat/username is just curse words.I curse myself but the school doesnt like it. So what i used to do it turn of chat. But then i cant use commands

**Comment by LAX1DUDE** [comment]
> I play this in school and most of the chat/username is just curse words.I curse myself but the school doesnt like it. So what i used to do it turn of chat. But then i cant use commands

Making a chat filter is like playing whack-a-mole, I’d constantly have to add more words because these people are just gonna make up new ones. I’ll download a chat filter and put it on the servers but I can’t read server logs to add new ones every day
