### ISSUE TITLE
Eaglecraft offline mode

### ISSUE THREAD

**Issue by Aircraft5** [LAX1DUDE/eaglercraft#63]
I have been trying to run Eaglecraft on my Chromebook offline, I have downloaded the offline html file, and when I open the file it runs fine, the issue is I can't join any worlds, I tried following the instructions, I entered 127.0.0.1:25565 into the direct connect, I tried other ports also, but nothing worked, I think the issue might be i'm not running a webserver, i'm just opening the file and it runs in my browser when i'm offline. 

I can't figure out how to play offline, if anyone has any suggestions that would be awesome. 

Thanks for taking the time to read this.

**Comment by LAX1DUDE** [comment]
Did you watch the video? You’re supposed to open the two batch files in the java folder of ‘stable-download’, if you’re not seeing two black and white terminal windows then please watch my server setup guide [https://youtu.be/Zsnv8YskjMA](https://youtu.be/Zsnv8YskjMA)

**Comment by Aircraft5** [comment]
Yeah I watched the video, but I think I just realized what the issue is, this is my school Chromebook, and they managed to disable the terminal, so I don't think I can run the run.bat file. As far as I can see there are no work arounds. Sorry for wasting your time, have a great day!
