### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by yourmomstinkz** [LAX1DUDE/eaglercraft#66]
its too laggy

**Comment by broiscool** [comment]
dum dum its because the severs are over loaded make your own sever hear https://replit.com/@ayunami2000/eaglercraft-server?v=1

**Comment by literally1984** [comment]
Also, it might be because your settings aren't optimized. For me, I went from 2 fps to 60 by going in video settings and making render distance short and by putting performance to Max FPS.

**Comment by LAX1DUDE** [comment]
> its too laggy

![https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png](https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png)
