### ISSUE TITLE
Need help to find servers to play on.

### ISSUE THREAD

**Issue by TSStrategy** [LAX1DUDE/eaglercraft#67]
It would be really helpful if there was a guide to help find servers that work for this. A website with a list of servers would help too.

**Comment by literally1984** [comment]
Somebody said that there was a list on the discord server.

**Comment by TSStrategy** [comment]
> Somebody said that there was a list on the discord server.

Oh, well if anyone has the IP of one of the servers that would be really helpful.

**Comment by TSStrategy** [comment]
Also, it says that you can join real 1.5.2 servers but I cant

**Comment by aydanmassa** [comment]
i have a survival server you can join if you want



> It would be really helpful if there was a guide to help find servers that work for this. A website with a list of servers would help too.

i

**Comment by LAX1DUDE** [comment]
> It would be really helpful if there was a guide to help find servers that work for this. A website with a list of servers would help too.

I'm making a forum for servers instead of spamming them in discord channels

**Comment by LAX1DUDE** [comment]
> Also, it says that you can join real 1.5.2 servers but I cant

Yeas it can, it says you need to set up a proxy
