### ISSUE TITLE
Servers are always overloaded. (Suggestion)

### ISSUE THREAD

**Issue by that-one-gamer1015** [LAX1DUDE/eaglercraft#70]
You should make a patreon or something so that you can get better servers.

**Comment by LAX1DUDE** [comment]
If I start accepting money then this is gonna be a much bigger problem for microsoft and mojang if they decide to care. I have a whole life ahead of me and getting caught in some piracy lawsuit is only gonna make it harder for me to get a programing job when I already have no degree or referrals or anything.
