### ISSUE TITLE
[ChromeOS] Game ran fine in past, game is now unplayable.

### ISSUE THREAD

**Issue by EnderIsBasic** [LAX1DUDE/eaglercraft#71]
I am hosting my own server, and the game use to run at 30 on average, it now seems to run at 2 fps, 3 at max.

Any ideas?

**Comment by LAX1DUDE** [comment]
> I am hosting my own server, and the game use to run at 30 on average, it now seems to run at 2 fps, 3 at max.
> 
> Any ideas?

make sure the game is not already open on a different tab of the browser

**Comment by EnderIsBasic** [comment]
> > I am hosting my own server, and the game use to run at 30 on average, it now seems to run at 2 fps, 3 at max.
> > 
> > Any ideas?
> 
> make sure the game is not already open on a different tab of the browser

I've made sure and it's still not working

**Comment by EnderIsBasic** [comment]
never mind, someone had built a hopper chain across map
