### ISSUE TITLE
Survival problems

### ISSUE THREAD

**Issue by eldercraftlover** [LAX1DUDE/eaglercraft#72]
you cant enter any portal in survival rn

**Comment by LAX1DUDE** [comment]
![https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png](https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png)
![https://i.gyazo.com/7fb679daaaa362784128aaea5717addd.png](https://i.gyazo.com/7fb679daaaa362784128aaea5717addd.png)
