### ISSUE TITLE
ConnectException: Connection timed out: null

### ISSUE THREAD

**Issue by FocalFossa0997** [LAX1DUDE/eaglercraft#73]
I am trying to play this on a school chromebook. The default creative server does not load, I get something like this instead:

![image](https://user-images.githubusercontent.com/69269521/152273657-e6e9e586-e297-4b85-b674-bbc861af9637.png)

Here is the expected behavior:
https://user-images.githubusercontent.com/69269521/152274176-33516b46-0a89-4d6f-8730-e947938e34d0.mp4

how do I fix this?

**Comment by ethanaobrien** [comment]
Chances are your school has the site blocked (like mine). Can you access https://g.eags.us/eaglercraft/ ?

**Comment by LAX1DUDE** [comment]
> I am trying to play this on a school chromebook. The default creative server does not load, I get something like this instead:

![https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png](https://i.gyazo.com/f9ecf6e91d3e34e5e15f5ad95980c41f.png)
