### ISSUE TITLE
404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by pogdotexe** [LAX1DUDE/eaglercraft#74]
Hi, when I startup the server that I have hosted on repl.it with a custom domain, it shows up this 
![image](https://user-images.githubusercontent.com/78807240/152352499-81ea3096-a2bc-47a3-a656-05a3bec362f1.png)

**Comment by ayunami2000** [comment]
This happens sometimes with the repl, please send repl issues to the discord as it is unrelated. Basically this happens sometimes and for a quick fix just use a different client and connect to wss://domain/server to join the server
