### ISSUE TITLE
How do you host a privet server? 

### ISSUE THREAD

**Issue by MeekHercules389** [LAX1DUDE/eaglercraft#75]
How do you host a server?(please be Detailed)

**Comment by aydanmassa** [comment]
search up lax1dude on youtube he made a video on it

**Comment by LAX1DUDE** [comment]
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/59](https://github.com/LAX1DUDE/eaglercraft/issues/59)
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/52](https://github.com/LAX1DUDE/eaglercraft/issues/52)
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/32](https://github.com/LAX1DUDE/eaglercraft/issues/32)
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/31](https://github.com/LAX1DUDE/eaglercraft/issues/31)
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/22](https://github.com/LAX1DUDE/eaglercraft/issues/22)
Issue [https://github.com/LAX1DUDE/eaglercraft/issues/14](https://github.com/LAX1DUDE/eaglercraft/issues/14)

[https://youtu.be/Zsnv8YskjMA](https://youtu.be/Zsnv8YskjMA)

Please try harder next time
