### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by THEBEST1278** [LAX1DUDE/eaglercraft#81]
hello i was joining the game from the download and it said failed to connect to server and I was wondering if there was a way to fix this

**Comment by LAX1DUDE** [comment]
What server? What device? What browser? Are you at a school? I can't answer questions like this there are a million reasons it might not connect, there's no 'fix' I can give you with the information you've provided.

Issue #73
Issue #57
Issue #53 
Issue #49 
Issue #29 
Issue #25
Issue #24
Issue #19
