### ISSUE TITLE
Chromebook Server Hosting

### ISSUE THREAD

**Issue by Parcival157** [LAX1DUDE/eaglercraft#82]
I watched the video for a PC, but most people are on chromebook and cant do all the same things, can you help with hosting a server on chromebook?

Or if someone else could host a server for me and my freind that would be great

**Comment by THEBEST1278** [comment]
yea idk how to host a server pls help

**Comment by THEBEST1278** [comment]
ik you explained in the bottom of the page but I don't understand anything not even in the video can you give us the minute the part of downloading the game is in the video

**Comment by IronicallyMdd** [comment]
read. join their discord.

**Comment by THEBEST1278** [comment]
I don't understand what the readme says but ok whatever

**Comment by LAX1DUDE** [comment]
> I watched the video for a PC, but most people are on chromebook and cant do all the same things, can you help with hosting a server on chromebook?

You can't run the JRE on a chromebook, I might/could implement a form of LAN worlds eventually but it's not possible to make the existing multiplayer code work on a school chromebook.

**Comment by Parcival157** [comment]
Thanks for being an active helper (:
