### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by tyler6974** [LAX1DUDE/eaglercraft#87]
if you fly above a ender portal it the image gets zoomed in and water and lava look weird when it is in its flowing stage and then if you turn off the fix bug #4994 everything just gets blurry and ender pearls dont do anything

**Comment by LAX1DUDE** [comment]
> if you fly above a ender portal it the image gets zoomed in

That's how it looks in vanilla

> and water and lava look weird when it is in its flowing stage

This is an older version of minecraft that's how it looks in vanilla 

> and then if you turn off the fix bug #4994 everything just gets blurry

Bruh it says 'fix bug' what part of 'fix bug' doesn't explain why the game looking glitched when you intentionally turn it off


> and ender pearls dont do anything

You're in creative mode
