### ISSUE TITLE
follow up to the other

### ISSUE THREAD

**Issue by tyler6974** [LAX1DUDE/eaglercraft#88]
![Screenshot 2022-02-07 175550](https://user-images.githubusercontent.com/92064448/152886259-1e7a4984-33b1-44ae-9cb0-429f1f0503c1.png)
![Screenshot 2022-02-07 175547](https://user-images.githubusercontent.com/92064448/152886261-1ca846f2-aa2a-4599-9cd7-ff2ffd070eb4.png)
 
the fix bug button makes the textures look weird and the other screenshot shows it

**Comment by LAX1DUDE** [comment]
#87

**Comment by LAX1DUDE** [comment]
don't open multiple issues
