### ISSUE TITLE
How do i make a texture pack and use it in either the creative or survival servers?

### ISSUE THREAD

**Issue by stin-stin** [LAX1DUDE/eaglercraft#89]
If someone knew how to or if there is a video on how to that would be great. Thanks.

**Comment by LAX1DUDE** [comment]
You can't upload a custom texture pack on the demo site if that's what you mean by "the creative or survival servers". If you set up your own website and server (which I strongly recommend) then you can use the [epkcompiler](https://github.com/LAX1DUDE/eaglercraft/tree/main/epkcompiler) and compile your own version of the `assets.epk` file to change all the textures that way but there's no way to replace all the textures on my demo site.
