### ISSUE TITLE
Multiple Servers on a Bungeecord Network don't work

### ISSUE THREAD

**Issue by MegaTKC** [LAX1DUDE/eaglercraft#9]
I am currently trying to add multiple servers to a bungeecord network. If I do so, it works, but I try to connect to the second server through bungee it redirects me to another page on chrome and it just doesn't work. Is there a way to get multiple servers on bungee to work?

**Comment by LAX1DUDE** [comment]
What is the URL of the page it is redirecting to, there is no code in eaglercraft for redirecting the current page there is only code to open new tabs. Only the 'Fork on Github' button and the link confirmation screen you get when you click a link in chat have the ability to redirect the page and they are both programmed to open a new tab.

**Comment by LAX1DUDE** [comment]
see the bungeecord configuration guide, there have been no changes made to bungeecord's core functionality, If I still had the github commits documenting my changes you would understand what I mean. I did not edit any part of bungeecord I just added a thread that is launched independently from the rest of the program from the main class that proxies incoming websocket connections to forward as real loopback vanilla minecraft TCP connections to the regular bungeecord listener running in the same process.

[https://www.spigotmc.org/wiki/bungeecord-configuration-guide/](https://www.spigotmc.org/wiki/bungeecord-configuration-guide/)

**Comment by LAX1DUDE** [comment]
if just using a single server worked fine then there's nothing wrong with any of the changes I specifically made

**Comment by ayunami2000** [comment]
Can you make your modifications into a separate bungeecord plugin possibly, so I can use it with the latest bungeecord?

**Comment by LAX1DUDE** [comment]
Post your bungeecord config file

**Comment by MegaTKC** [comment]
https://user-images.githubusercontent.com/59368582/149041883-877438f4-a54c-48c5-9897-1d8093653b08.mp4

I've hosted the client on one of my servers.

> What is the URL of the page it is redirecting to, there is no code in eaglercraft for redirecting the current page there is only code to open new tabs. Only the 'Fork on Github' button and the link confirmation screen you get when you click a link in chat have the ability to redirect the page and they are both programmed to open a new tab.

**Comment by LAX1DUDE** [comment]
That is not a bungeecord configuration file. And those are not server hyperlinks in your chat.

Support for JSON chat formatting was never added to minecraft until 1.7.2. You are experiencing a client side glitch that is meant to automatically hook all messages containing a regular http:// or https:// URL that players might've typed in the chat to make it easy to other players on the server to open these links quickly (I already mentioned this to a degree in my initial comment). You do not switch between servers in bungeecord by opening an HTTP hyperlink in a new tab at a totally different URL from the Eaglercraft HTML file you are playing on that makes no sense, that is not how bungeecord works you did not read the configuration guide.

See the JSON chat formatting changelog [https://minecraft.fandom.com/wiki/Raw_JSON_text_format](https://minecraft.fandom.com/wiki/Raw_JSON_text_format)

Use something like iPortal on your craftbukkit instances to facilitate quick travel between the bungeecord servers [https://www.spigotmc.org/resources/iportal-transportation-bungeecord-portals.29552/](https://www.spigotmc.org/resources/iportal-transportation-bungeecord-portals.29552/)

**Comment by LAX1DUDE** [comment]
I fixed the link clicking glitch you experienced here while you were trying to switch servers, only valid HTTP URLs typed in the chat will now open a tab when they are clicked. All other text is ignored, and by HTTP I mean a link to a page on a regular website, there is no support for making clickable server links in the chat.

Download the updated classes.js here to avoid confusion [https://github.com/LAX1DUDE/eaglercraft/tree/main/stable-download/web](https://github.com/LAX1DUDE/eaglercraft/tree/main/stable-download/web)

**Comment by MegaTKC** [comment]
> I fixed the link clicking glitch you experienced here while you were trying to switch servers, only valid HTTP URLs typed in the chat will now open a tab when they are clicked. All other text is ignored, and by HTTP I mean a link to a page on a regular website, there is no support for making clickable server links in the chat.
> 
> Download the updated classes.js here to avoid confusion https://github.com/LAX1DUDE/eaglercraft/tree/main/stable-download/web

Thanks! I also figured out I can do `/server hub-01` to connect to another server on bungee.
