### ISSUE TITLE
what is up with the server

### ISSUE THREAD

**Issue by CloudClownn** [LAX1DUDE/eaglercraft#92]
for some reason, there is no way to get in the server right now I heard they are testing dome stuff is that true if it's not why can't I join the server thank you

**Comment by JVGA8837** [comment]
they shut down

**Comment by CloudClownn** [comment]
why

**Comment by LAX1DUDE** [comment]
I was very clear with my message posted on g.eags.us, I said don't open any issues on my GitHub.
