### ISSUE TITLE
Is There A Way how to Make your own client thingy

### ISSUE THREAD

**Issue by banana-nana** [LAX1DUDE/eaglercraft#94]

**Comment by LAX1DUDE** [comment]
define client for me

**Comment by banana-nana** [comment]
Like the website https://g.eags.us/ but, its not working would there be a way to make it deployable to heroku or replt

**Comment by banana-nana** [comment]
Same with my Unblocker aka fakeschoology.herokuapp.com/ and type in the url it comes up with about:blank

**Comment by LAX1DUDE** [comment]
[https://github.com/LAX1DUDE/eaglercraft#installing](https://github.com/LAX1DUDE/eaglercraft#installing)

[https://www.youtube.com/watch?v=Zsnv8YskjMA](https://www.youtube.com/watch?v=Zsnv8YskjMA)
