### ISSUE TITLE
Add More Ram to Server Warning

### ISSUE THREAD

**Issue by MopNop** [LAX1DUDE/eaglercraft#98]
I have a server hosted on Replit and it is telling me I should raise the amount of allocated ram, though I have. Here is the warning:
" **[WARNING] To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"** "
I have raised the amount of memory in the run.bat file but it doesn't seem to change. Is there a way to fix this?

**Comment by LAX1DUDE** [comment]
I didn't create the replit version, please ask ayunami2000. The run.bat file is windows-only, replit is linux so run.bat is not the script that launches the server in your config, it is just a file left over from me debugging the 'official' system on my windows computer. 

You can ask questions or reinstall your replit from [ayunami2000/eaglercraft-replit](https://github.com/ayunami2000/eaglercraft-replit)

**Comment by MopNop** [comment]
Ok thank you
